### Crear un registro de sensores
POST https://backendstresswatch.onrender.com/api/sensores
Content-Type: application/json

{

  "heartRate": 7232232,
  "light": 363.2,
  "gyro": 253,
  "timestamp:": 8523,
  "userId": "2342352"
}


### Obtener el último registro
GET http://localhost:3000/api/sensores/ultimo

###
### Actualizar un registro por ID
PUT http://localhost:3000/api/sensores/{{}}
Content-Type: application/json

{
  "pulso": 90
}
