### Crear un registro de sensores
POST https://backendstresswatch.onrender.com/api/sensores
Content-Type: application/json

{

  "heartRate": 7232223423432,
  "light": 363.2,
  "gyro": 253,
  "timestamp": 1,
  "userId": "234232342352"
}


### Obtener el último registro
GET http://localhost:3000/api/sensores/ultimo

###
### Actualizar un registro por ID
PUT http://localhost:3000/api/sensores/{{}}
Content-Type: application/json

{
  "pulso": 90
}

###
POST https://backendstresswatch.onrender.com/api/auth/register
Content-Type: application/json

{
  "nombre": "Chrisdsadasdsasdsaddafs",
  "apellido": "Hesssrnasdsadández",
  "edad": "25",
  "sexo": "Masculino",
  "fechaNacimiento": "2000-03-12",
  "pais": "México",
  "usuario": "alee@gmail.com",
  "password": "123",
  "avatarIndex": "1"
}

###
POST https://backendstresswatch.onrender.com/api/auth/login
Content-Type: application/json

{
  "usuario": "alee@gmail.com",
  "password": "123"
}
