### Crear un registro de sensores
POST https://backendstresswatch.onrender.com/api/sensores
Content-Type: application/json

{

  "heartRate": 7232223423432,
  "light": 363.2,
  "gyro": 253,
  "timestamp": 1,
  "userId": "234232342352"
}


### Obtener el último registro
GET http://localhost:3000/api/sensores/ultimo

###
### Actualizar un registro por ID
PUT http://localhost:3000/api/sensores/{{}}
Content-Type: application/json

{
  "pulso": 90
}

###
POST https://backendstresswatch.onrender.com/api/auth/register
Content-Type: application/json

{
  "nombre": "Chris",
  "apellido": "Hernández",
  "sexo": "masculino",
  "fechaNacimiento": "2000-05-12",
  "imagenPerfil": "https://cdn.miapp.com/perfiles/chris.png",
  "pais": "México",
  "usuario": "chris123",
  "password": "123456"
}

###
POST https://backendstresswatch.onrender.com/api/auth/login
Content-Type: application/json

{
  "usuario": "chris123",
  "password": "123456"
}
