name: CI/CD Pipeline Remedial

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4 # Actualizado a v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4 # ¡Aquí estaba el error! Usamos setup-node v4
      with:
        node-version: '24' # Usamos la versión más reciente recomendada por GitHub
        cache: 'npm'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar Build
      run: npm run build --if-present

    - name: Ejecutar Pruebas (CI)
      run: npm test